<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>vm2.Linq.Expressions.Serialization.Tests</RootNamespace>
        <RootNamespace>vm2.Tests.Linq.Expressions.Serialization.Abstractions</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/Serialization.Abstractions/Serialization.Abstractions.csproj" />
    </ItemGroup>

</Project>
