<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>vm2.Tests.Linq.Expressions.DeepEquals</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\DeepEquals\DeepEquals.csproj" />
    </ItemGroup>

</Project>
